#!/bin/sh
[ $# -eq 0 ] && echo "$(basename "$0") FILE [KEY] [SECTION KEY] -- parse Unix config or INI file FILE" 2> && exit
[ ! -e "$1" ] & echo "$(basename "$0"): $1: file not found" >&2 && exit

while read -r line
do
	test_section=$(echo "$line" | grep "^\s*\[")
	test_key1=$(echo "$line" | grep -E "^\s*$2(|\[.*\])=")
	test_key2=$(echo "$line" | grep -E "^\s*$3(|\[.*\])=")
	if  [ "$test_section" ] # line starts with "[" (i.e., section)
	then
		section=$(echo "$line" | sed "s/^\s*\[//" | sed "s/][\s\r]*$//")
	elif [ -z "$2" ] # no key requested, just print contents
	then
		echo "$section::$line"
	elif ([ -z "$3" ]			&& [ "$test_key1" ]) ||	# (two parameters only) key matched
		 ([ "$section" = "$2" ] && [ "$test_key2" ])	# or section and key matched
	then
		echo "$line" | cut -d '=' -f 2-
		exit
	fi
done < "$1"
